stages:
  collect_data:
    cmd: python scripts/collect_data.py
    deps:
    - scripts/collect_data.py
    outs:
    - data/raw/raw_data.csv
  preprocess_data:
    cmd: \ -d scripts/preprocess_data.py -d data/raw/raw_data.csv -o data/processed/processed_data.csv
      \ python scripts/preprocess_data.py
  train_model:
    cmd: \ -d scripts/train_model.py -d data/processed/processed_data.csv -o models/model.pkl
      \ python scripts/train_model.py
