stages:
  collect_data:
    cmd: python scripts/collect_data.py
    deps:
    - scripts/collect_data.py
    outs:
    - data/raw/raw_data.csv
  preprocess_data:
    cmd: \ -d scripts/preprocess_data.py
    deps:
      - scripts/preprocess_data.py
      - data/raw/raw_data.csv
    outs:
      - data/processed/processed_data.csv
  train_model:
    cmd: \ -d scripts/train_model.py
    deps:
      - scripts/train_model.py
      - data/processed/processed_data.csv
    outs:
      - models/model.pkl
